import os

# car
CAR_SPRITE_SCALING = 0.4
# CAR_SPRITE_SIZE = int(SPRITE_NATIVE_SIZE * CAR_SPRITE_SCALING)
SPRITE_SCALING = 0.45
SPRITE_NATIVE_SIZE = 128
SPRITE_SIZE = int(SPRITE_NATIVE_SIZE * SPRITE_SCALING)
# coin
SPRITE_SCALING_COIN = 0.2


# Screen
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "FROGGER"

#movement
MOVEMENT_SPEED = 5
NO_MOVEMENT = 0

#car spacing
Y_COUNT = 5
Y_START = 100
Y_SPACING = 50

NUM_CARS_PER_ROW = 1

# lives
LIFE_COUNT = 3
LIFE_POSITION_START = 20
LIFE_SPACING = 20
GAME_OVER = 1
PLAY_GAME = 0

PICTURES_PATH = os.path.dirname(os.path.abspath(__file__)) + "/pictures/"

