import os

# car
SPRITE_SCALING = 0.5
SPRITE_NATIVE_SIZE = 128
SPRITE_SIZE = int(SPRITE_NATIVE_SIZE * SPRITE_SCALING)
# coin
SPRITE_SCALING_COIN = 0.2


# Screen
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "FROGGER"

#movement
MOVEMENT_SPEED = 10
NO_MOVEMENT = 0

#car spacing
Y_COUNT = 5
Y_START = 50
Y_SPACING = 100

PICTURES_PATH = os.path.dirname(os.path.abspath(__file__)) + "/pictures/"

